/**
 * Simple CUP file to generate numeric
 * values for the tokens to be returned
 * by Quant's lexer.
 *
 * Run with CUP to generte sym.java.
 */

import java_cup.runtime.*;

terminal VARIABLE;
terminal INTEGER;
terminal IS;
terminal PERIOD;
terminal PLUS;
terminal MINUS;
terminal TIMES;
terminal OVER;
terminal PRINT;

/* Dummy grammar--so CUP doesn't complain. */

non terminal dummy;
dummy ::= ;
