(**Question:  I have a circle with radius 10, and I have a square
with a whole-number width.  My square's area is larger than
my circle's area.  What is is the smallest width my square
can have?)

(I know I have a circle and a square...)
My circle is a circle.
My square is a square.

(And I know my circle's radius.)
My circle's radius is 10.

(What I can do is start from 1 and increase the width
until it isn't smaller than my circle's area anymore...)
My square's width is 1.

While my square's area is less than my circle's area,
set my square's width to my square's width plus 1.

(Show me the result!)
What is my square's width?
(Am I right?)
Is my square's area greater than my circle's area?


